version: '3.9'

services:
  keycloak-db:
    image: postgres:15.2-alpine
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Expose port for dev and debug purpose only
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
  keycloak-api:
    # image: quay.io/keycloak/keycloak:21.1.1 # Official Keycloak
    image: coopersoft/keycloak:21.0.2_phone-2.3.3
    depends_on:
      - keycloak-db
    volumes:
      - keycloak-api:/opt/keycloak/data
    ports:
      - 8080:8080 # backward compatibility
      - 8443:8443
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: unless-stopped
    command:
      - start-dev --spi-phone-default-service=dummy
  keycloak-healthcheck:
    image: curlimages/curl:latest
    command:
      - "sh"
      - "-c"
      - >
          while true; do
            sleep 3600;
          done
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://keycloak:8080/health" ]
      interval: 10s
      timeout: 60s
      retries: 5
    depends_on:
      - keycloak-api

volumes:
  keycloak-db:
  keycloak-api:
